"""Add estimated_minute column to schedule

Revision ID: 2233a32004a5
Revises: 7d8138de09a9
Create Date: 2026-01-11 14:25:31.142436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2233a32004a5'
down_revision: Union[str, Sequence[str], None] = '7d8138de09a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_task', sa.Column('estimated_minute', sa.Integer(), nullable=True))
    op.drop_column('sub_task', 'estimated_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_task', sa.Column('estimated_time', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('sub_task', 'estimated_minute')
    # ### end Alembic commands ###
