"""add_notify_at_and_is_sent_to_notification

Revision ID: 8df204b49245
Revises: 89e607f6ec8d
Create Date: 2026-01-15 06:51:31.334365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8df204b49245'
down_revision: Union[str, Sequence[str], None] = '89e607f6ec8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_pending')
    op.add_column('notifications', sa.Column('notify_at', sa.DateTime(), nullable=False))
    op.add_column('notifications', sa.Column('is_sent', sa.Boolean(), nullable=False))
    op.alter_column('notifications', 'schedule_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               nullable=True)
    op.add_column('schedule', sa.Column('estimated_minute', sa.Integer(), nullable=True))
    op.add_column('schedule', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('sub_task', sa.Column('priority', sa.String(length=20), nullable=True))
    op.add_column('sub_task', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('sub_task', sa.Column('tip', sa.Text(), nullable=True))
    op.alter_column('sub_task', 'schedule_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sub_task', 'schedule_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               nullable=False)
    op.drop_column('sub_task', 'tip')
    op.drop_column('sub_task', 'category')
    op.drop_column('sub_task', 'priority')
    op.drop_column('schedule', 'source')
    op.drop_column('schedule', 'estimated_minute')
    op.alter_column('notifications', 'schedule_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               nullable=False)
    op.drop_column('notifications', 'is_sent')
    op.drop_column('notifications', 'notify_at')
    op.create_table('ai_pending',
    sa.Column('pending_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('status', mysql.ENUM('PENDING', 'COMPLETED', 'CANCELLED'), nullable=False),
    sa.Column('intent', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False),
    sa.Column('draft_json', mysql.JSON(), nullable=False),
    sa.Column('missing_fields', mysql.JSON(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('pending_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
